export const VALUE = '[data-testid="value"]';
export const BUTTON = '[data-testid="button"]';
export const CIRCLE = '[data-testid="circle"]';
export const INDEX = '[data-testid="index"]';
export const HEAD = '[data-testid="head"]';
export const TAIL = '[data-testid="tail"]';
export const ADD_HEAD = '[data-testid="addHead"]';
export const DEL_HEAD = '[data-testid="delHead"]';
export const ADD_TAIL = '[data-testid="addTail"]';
export const DEL_TAIL = '[data-testid="delTail"]';
export const ADD_BY_INDEX = '[data-testid="addByIndex"]';
export const DEL_BY_INDEX = '[data-testid="delByIndex"]';
export const BORDER_PINK = "4px solid rgb(210, 82, 225)";
export const BORDER_BLUE = "4px solid rgb(0, 50, 255)";
export const BORDER_GREEN = "4px solid rgb(127, 224, 81)";
